version: '3.8'

services:
  cosyvoice-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosyvoice2-api
    ports:
      - "8012:8012"
    volumes:
      # Mount model directory (you need to place your models here)
      - ./pretrained_models:/app/pretrained_models
      # Mount voice cache for persistence
      - ./voice_cache:/app/voice_cache
      # Mount outputs for generated audio files
      - ./outputs:/app/outputs
      # Mount logs for debugging
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s
