name: cosyvoice2-api
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision
  - torchaudio=2.2.2
  - pytorch-cuda=12.1
  - librosa
  - soundfile
  - numpy
  - scipy
  - pip
  - pip:
    - fastapi>=0.104.0,<1.0.0
    - uvicorn[standard]>=0.24.0,<1.0.0
    - python-multipart>=0.0.6,<1.0.0
    - gunicorn>=21.0.0,<22.0.0
    - pydantic>=2.0.0,<3.0.0
    - pydantic-settings>=2.0.0,<3.0.0
    - transformers>=4.37.0,<5.0.0
    - modelscope==1.9.5
    - aiofiles==23.2.1
    - python-jose[cryptography]==3.3.0
    - httpx==0.25.2
    - tqdm==4.66.1
    - hyperpyyaml==1.2.2
    - onnxruntime==1.16.3
    - pypinyin==0.50.0
    - jieba==0.42.1
    - inflect==7.0.0
    - eng_to_ipa==0.0.2
    - unidecode==1.3.7
    - cn2an==0.5.22
    - num2words==0.5.13
    - openai-whisper>=20231117
    # - WeTextProcessing>=1.0.3  # Commented out due to compilation issues
    - pynini  # For text normalization
    - openfst-python  # OpenFST Python bindings
    # Additional dependencies discovered during setup
    - gradio
    - lightning
    - omegaconf
    - diffusers
    - hydra-core
    - gdown
    - matplotlib
    - wget
    - pyarrow
    - pyworld
    - wetext
    - conformer
    - seaborn
    - wandb
    - tensorboard
    - rich
    - setuptools
    - wheel
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.11.0
    - flake8==6.1.0
